///////////////////////////////////////////////////////////
//  Arena.cs
//  Implementation of the Class MyBrick
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2017 1:09:03 PM
//  Original author: 0849480
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Lego.Ev3.Core;
using Lego.Ev3.Desktop;

namespace LegoStormGrp5
{

    public class Arena
    {

        /// <summary>
        /// Contains Blue, Red, Black, Yellow {2 ,5 ,1 ,4 }
        /// </summary>
        public int[] HomeCnr;

        public int[] Colors = { 2, 5, 1, 4 };

        public Arena()
        {

        }

       

        public int GetLocation()
        {

            return 0;
        }

        /// <summary>
        /// Rotate 360 to determine the shortest distance.
        /// </summary>
        /// <param name="pGyro"></param>
        /// <param name="pDistance"></param>
        public int GetNearestWallColor(int pGyro, double pDistance)
        {

            return 0;
        }

        /// 
        /// <param name="pColorStart"></param>
        public int MovementLogic(int pColorStart)
        {
            
            int Left;
            var index = Array.IndexOf(Colors, pColorStart);

            switch (index)
            {
                case 0:
                    Left = 3;
                    break;

                default:
                    Left = index - 1;
                    break;
            }

            if (Colors[index] == HomeCnr[0] || Colors[index] == HomeCnr[1])
            {
                if (Colors[Left] == HomeCnr[0] || Colors[Left] == HomeCnr[1])
                {
                    return -90;
                }
                else
                {
                    return 90;
                }
            }
            else
            {
                return 180;
            }

        }

    }

    //end MyBrick
}