///////////////////////////////////////////////////////////
//  Connection.cs
//  Implementation of the Class Connection
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2017 1:09:14 PM
//  Original author: 0849480
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Lego.Ev3.Core;
using Lego.Ev3.Desktop;

namespace LegoStormGrp5
{

    public class Connection
    {

        public MyBrick m_MyBrick;

        public Connection()
        {

        }

        ~Connection()
        {

        }

        public int MakeConnection()
        {

            return 0;
        }

    }//end Connection
}