///////////////////////////////////////////////////////////
//  MyBrick.cs
//  Implementation of the Class Sensing
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2017 1:09:15 PM
//  Original author: 0849480
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Lego.Ev3.Core;
using Lego.Ev3.Desktop;

namespace LegoStormGrp5
{

    public class MyBrick
    {

        public Sensing m_Sensing;
        public Arena m_Arena;
        public Brick Brick { get; set; }

        public MyBrick()
        {
            
        }

        ~MyBrick()
        {

        }

        public string AlignToWall()
        {

            return "";
        }

        public async void MakeConnection()
        {
            Brick = new Brick(new UsbCommunication());
            await Brick.ConnectAsync();
        }

    }//end MyBrick
}