///////////////////////////////////////////////////////////
//  Sensing.cs
//  Implementation of the Class Arena
//  Generated by Enterprise Architect
//  Created on:      10-Nov-2017 1:09:15 PM
//  Original author: 0849480
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Lego.Ev3.Core;
using Lego.Ev3.Desktop;

namespace LegoStormGrp5
{
    public class Arena {

        /// <summary>
        /// Contains RED, BLACK, YELLOW, BLUE
        /// </summary>
        public string HomeCnr[];

        public Arena() {

        }

        ~Arena() {

        }

        public int GetLocation() {

            return 0;
        }

        /// <summary>
        /// Rotate 360 to determine the shortest distance.
        /// </summary>
        /// <param name="pGyro"></param>
        /// <param name="pDistance"></param>
        public int GetNearestWallColor(int pGyro, double pDistance) {

            return 0;
        }

        /// 
        /// <param name="pColorStart"></param>
        public int MovementLogic(int pColorStart) {

            return 0;
        }

    }//end Arena
}